experiment:
  device: cuda:0
model:
  latent: 5
  loss:
    beta: 1.0
  epochs: 5
  lr: 0.0001
  optimizer: adam
  batch_size: 96

loader:
  load_folder:
    folder: C:/Users/Cristobal/Desktop/ADNI_BIDS
    prefix: r
    extension: .nii
    target_folder_name: pet
  splits:
  - 0.8
  - 0.10
  - 0.10

