experiment:
  device: cuda:0
model:
  latent: 5
  loss:
    beta: 1.0
  epochs: 5
  lr: 0.01
  optimizer: adam
  batch_size: 4

loader:
  load_folder:
    folder: C:/Users/Cristobal/Desktop/DATOS_PRUEBA
    prefix: r
    extension: .nii
    target_folder_name: pet
  splits:
  - 0.7
  - 0.15
  - 0.15

